// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZKDeviceManager.Data;

#nullable disable

namespace ZKDeviceManager.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260810140440_AttendanceLogsAndCopySelection")]
    partial class AttendanceLogsAndCopySelection
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ZKDeviceManager.Data.Entities.AttendanceLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<string>("DeviceUserId")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<DateTime>("DownloadedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("InOutMode")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("VerifyMode")
                        .HasColumnType("int");

                    b.Property<int>("WorkCode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "DeviceUserId", "Timestamp")
                        .IsUnique();

                    b.ToTable("AttendanceLogs");
                });

            modelBuilder.Entity("ZKDeviceManager.Data.Entities.BiometricTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DownloadedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("EnrolledUserId")
                        .HasColumnType("int");

                    b.Property<int>("FingerIndex")
                        .HasColumnType("int");

                    b.Property<int>("Flag")
                        .HasColumnType("int");

                    b.Property<int>("Length")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EnrolledUserId", "Type", "FingerIndex");

                    b.ToTable("BiometricTemplates");
                });

            modelBuilder.Entity("ZKDeviceManager.Data.Entities.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CommKey")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirmwareVersion")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastSeenUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Platform")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("IpAddress", "Port")
                        .IsUnique();

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("ZKDeviceManager.Data.Entities.EnrolledUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CardNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("DeviceUserId")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastDownloadedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Privilege")
                        .HasColumnType("int");

                    b.Property<int>("SourceDeviceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SourceDeviceId", "DeviceUserId")
                        .IsUnique();

                    b.ToTable("EnrolledUsers");
                });

            modelBuilder.Entity("ZKDeviceManager.Data.Entities.SyncJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FinishedUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IncludeCards")
                        .HasColumnType("bit");

                    b.Property<bool>("IncludeFaces")
                        .HasColumnType("bit");

                    b.Property<bool>("IncludeFingerprints")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("Progress")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("TargetDeviceId")
                        .HasColumnType("int");

                    b.Property<int>("Total")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("TargetDeviceId");

                    b.ToTable("SyncJobs");
                });

            modelBuilder.Entity("ZKDeviceManager.Data.Entities.AttendanceLog", b =>
                {
                    b.HasOne("ZKDeviceManager.Data.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("ZKDeviceManager.Data.Entities.BiometricTemplate", b =>
                {
                    b.HasOne("ZKDeviceManager.Data.Entities.EnrolledUser", "EnrolledUser")
                        .WithMany("Templates")
                        .HasForeignKey("EnrolledUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnrolledUser");
                });

            modelBuilder.Entity("ZKDeviceManager.Data.Entities.EnrolledUser", b =>
                {
                    b.HasOne("ZKDeviceManager.Data.Entities.Device", "SourceDevice")
                        .WithMany("Users")
                        .HasForeignKey("SourceDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceDevice");
                });

            modelBuilder.Entity("ZKDeviceManager.Data.Entities.SyncJob", b =>
                {
                    b.HasOne("ZKDeviceManager.Data.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ZKDeviceManager.Data.Entities.Device", "TargetDevice")
                        .WithMany()
                        .HasForeignKey("TargetDeviceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Device");

                    b.Navigation("TargetDevice");
                });

            modelBuilder.Entity("ZKDeviceManager.Data.Entities.Device", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ZKDeviceManager.Data.Entities.EnrolledUser", b =>
                {
                    b.Navigation("Templates");
                });
#pragma warning restore 612, 618
        }
    }
}
